### ISSUE TITLE
Error for auto

### ISSUE THREAD

**Issue by angweekiat** [forcasualplayers/cpp.property#1]
Possible workaround for 
`auto b = a.i; `

would be to list the constructors as explicit so as to throw a compile error:
```
explicit property() = default;
explicit property(const property &) = default;
explicit property(property &) = default;

```
Users can still do
```
auto b = fcp::property<int, &A::get_i, &A::set_i>(this->i);
```
within the context of A class since get_i and set_i are private members, but at that point, it's pretty much their fault already

**Comment by hhkit** [comment]
Consider my mind blown, I did not know that you could explicit the copy constructor. And it works like a charm.

Thanks for the suggestion, Wee Kiat!
